---
- name: Install and configure a kitten web page on backends
  hosts: backends
  vars:
    helloworld: Coucou
  tasks:
    - name: Ensure package nginx is installed
      apt:
        name: nginx
        state: latest
    - name: Ensure service nginx is running
      service:
        name: nginx
        state: started
    - name: Configure Kitten Page
      template:
        src: templates/index.j2
        dest: /var/www/html/index.html
    - name: Configure Nginx to listen on vrack
      template:
        src: templates/default.j2
        dest: /etc/nginx/sites-available/default
      notify:
        - Restart nginx
  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
- name: Install and haproxy on front
  hosts: front
  tasks:
    - name: Ensure package haproxy is installed
      apt:
        name: haproxy
        state: latest
    - name: Ensure service haproxy is running
      service:
        name: haproxy
        state: started
    - name: Configure haproxy
      template:
        src: templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify:
        - Reload haproxy
  handlers:
    - name: Reload haproxy
      ansible.builtin.service:
        name: haproxy
        state: reloaded
